// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MarketCredentials struct {
	Name   string `json:"name"`
	Token  string `json:"token"`
	APIURL string `json:"apiUrl"`
}

type MarketCredentialsInput struct {
	Name   string `json:"name"`
	APIURL string `json:"apiUrl"`
	Token  string `json:"token"`
}

type MemStats struct {
	Alloc      string `json:"alloc"`
	TotalAlloc string `json:"totalAlloc"`
	Sys        string `json:"sys"`
}

type Settings struct {
	Slot              *SlotSettings        `json:"slot"`
	MarketCredentials []*MarketCredentials `json:"marketCredentials"`
	MarketProvider    string               `json:"marketProvider"`
}

type SlotSettings struct {
	Volume int `json:"volume"`
}

type SlotSettingsInput struct {
	Volume int `json:"volume"`
}

type StockItem struct {
	Ticker            string   `json:"ticker"`
	Figi              string   `json:"figi"`
	Isin              *string  `json:"isin"`
	MinPriceIncrement *float64 `json:"minPriceIncrement"`
	Lot               *int     `json:"lot"`
	Currency          *string  `json:"currency"`
	Name              *string  `json:"name"`
	AmountLimit       float64  `json:"amountLimit"`
	TransactionLimit  int      `json:"transactionLimit"`
}

type StockItemInput struct {
	Ticker           string  `json:"ticker"`
	Figi             string  `json:"figi"`
	AmountLimit      float64 `json:"amountLimit"`
	TransactionLimit int     `json:"transactionLimit"`
}

type User struct {
	Email  string  `json:"email"`
	Name   *string `json:"name"`
	Avatar *string `json:"avatar"`
}
