// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MemStats struct {
	Alloc      string `json:"alloc"`
	TotalAlloc string `json:"totalAlloc"`
	Sys        string `json:"sys"`
}

type StockItem struct {
	Ticker           string  `json:"ticker"`
	Figi             string  `json:"figi"`
	AmountLimit      float64 `json:"amountLimit"`
	TransactionLimit int     `json:"transactionLimit"`
}

type StockItemInput struct {
	Ticker           string  `json:"ticker"`
	Figi             string  `json:"figi"`
	AmountLimit      float64 `json:"amountLimit"`
	TransactionLimit int     `json:"transactionLimit"`
}

type User struct {
	Email  string  `json:"email"`
	Name   *string `json:"name"`
	Avatar *string `json:"avatar"`
}
