name: Create release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Git Release
          uses: anton-yurchenko/git-release@v3.4.3
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
